const weaponMap = {
  'Ada': ['Blasters', 'Spear'],
  'Arcadia': ['Great Sword', 'Spear'],
  'Artemis': ['Rocket Lance', 'Scythe'],
  'Asuri': ['Katars', 'Sword'],
  'Azoth': ['Axe', 'Bow'],
  'Barraza': ['Axe', 'Blasters'],
  'Bodvar': ['Hammer', 'Sword'],
  'Brynn': ['Axe', 'Spear'],
  'Caspian': ['Gauntlets', 'Katars'],
  'Cassidy': ['Blasters', 'Hammer'],
  'Cross': ['Blasters', 'Gauntlets'],
  'Diana': ['Blasters', 'Bow'],
  'Dusk': ['Orb', 'Spear'],
  'Ember': ['Bow', 'Katars'],
  'Ezio': ['Orb', 'Sword'],
  'Fait': ['Orb', 'Scythe'],
  'Gnash': ['Hammer', 'Spear'],
  'Hattori': ['Spear', 'Sword'],
  'Isaiah': ['Blasters', 'Cannon'],
  'Jaeyun': ['Great Sword', 'Sword'],
  'Jhala': ['Axe', 'Sword'],
  'Jiro': ['Scythe', 'Sword'],
  'Kaya': ['Bow', 'Spear'],
  'Koji': ['Bow', 'Sword'],
  'Kor': ['Gauntlets', 'Hammer'],
  'Lin Fei': ['Cannon', 'Katars'],
  'Lord Vraxx': ['Blasters', 'Rocket Lance'],
  'Lucien': ['Blasters', 'Katars'],
  'Magyar': ['Great Sword', 'Hammer'],
  'Mako': ['Great Sword', 'Katars'],
  'Mirage': ['Scythe', 'Spear'],
  'Mordex': ['Gauntlets', 'Scythe'],
  'Munin': ['Bow', 'Scythe'],
  'Nix': ['Blasters', 'Scythe'],
  'Onyx': ['Cannon', 'Gauntlets'],
  'Orion': ['Rocket Lance', 'Spear'],
  'Petra': ['Gauntlets', 'Orb'],
  'Queen Nai': ['Katars', 'Spear'],
  'Ragnir': ['Axe', 'Katars'],
  'Rayman': ['Axe', 'Gauntlets'],
  'Reno': ['Blasters', 'Orb'],
  'Scarlet': ['Hammer', 'Rocket Lance'],
  'Sentinel': ['Hammer', 'Katars'],
  'Sidra': ['Cannon', 'Sword'],
  'Sir Roland': ['Rocket Lance', 'Sword'],
  'Teros': ['Axe', 'Hammer'],
  'Tezca': ['Boots', 'Gauntlets'],
  'Thatch': ['Blasters', 'Sword'],
  'Thor': ['Hammer', 'Orb'],
  'Ulgrim': ['Axe', 'Rocket Lance'],
  'Val': ['Gauntlets', 'Sword'],
  'Vector': ['Bow', 'Rocket Lance'],
  'Volkov': ['Axe', 'Scythe'],
  'Wu Shang': ['Gauntlets', 'Spear'],
  'Xull': ['Axe', 'Cannon'],
  'Yumiko': ['Bow', 'Hammer'],
  'Zariel': ['Bow', 'Gauntlets'],
}

export default weaponMap;