type WeaponTuple = [string, string]

type WeaponMap = {
  [key: string]: WeaponTuple;
}

const weaponMap: WeaponMap = {
  'ada': ['Blasters', 'Spear'],
  'arcadia': ['Great Sword', 'Spear'],
  'artemis': ['Rocket Lance', 'Scythe'],
  'asuri': ['Katars', 'Sword'],
  'azoth': ['Axe', 'Bow'],
  'barraza': ['Axe', 'Blasters'],
  'bodvar': ['Hammer', 'Sword'],
  'brynn': ['Axe', 'Spear'],
  'caspian': ['Gauntlets', 'Katars'],
  'cassidy': ['Blasters', 'Hammer'],
  'cross': ['Blasters', 'Gauntlets'],
  'diana': ['Blasters', 'Bow'],
  'dusk': ['Orb', 'Spear'],
  'ember': ['Bow', 'Katars'],
  'ezio': ['Orb', 'Sword'],
  'fait': ['Orb', 'Scythe'],
  'gnash': ['Hammer', 'Spear'],
  'hattori': ['Spear', 'Sword'],
  'isaiah': ['Blasters', 'Cannon'],
  'jaeyun': ['Great Sword', 'Sword'],
  'jhala': ['Axe', 'Sword'],
  'jiro': ['Scythe', 'Sword'],
  'kaya': ['Bow', 'Spear'],
  'koji': ['Bow', 'Sword'],
  'kor': ['Gauntlets', 'Hammer'],
  'lin fei': ['Cannon', 'Katars'],
  'lord vraxx': ['Blasters', 'Rocket Lance'],
  'lucien': ['Blasters', 'Katars'],
  'magyar': ['Great Sword', 'Hammer'],
  'mako': ['Great Sword', 'Katars'],
  'mirage': ['Scythe', 'Spear'],
  'mordex': ['Gauntlets', 'Scythe'],
  'munin': ['Bow', 'Scythe'],
  'nix': ['Blasters', 'Scythe'],
  'onyx': ['Cannon', 'Gauntlets'],
  'orion': ['Rocket Lance', 'Spear'],
  'petra': ['Gauntlets', 'Orb'],
  'queen nai': ['Katars', 'Spear'],
  'ragnir': ['Axe', 'Katars'],
  'rayman': ['Axe', 'Gauntlets'],
  'reno': ['Blasters', 'Orb'],
  'scarlet': ['Hammer', 'Rocket Lance'],
  'sentinel': ['Hammer', 'Katars'],
  'sidra': ['Cannon', 'Sword'],
  'sir roland': ['Rocket Lance', 'Sword'],
  'teros': ['Axe', 'Hammer'],
  'tezca': ['Boots', 'Gauntlets'],
  'thatch': ['Blasters', 'Sword'],
  'thor': ['Hammer', 'Orb'],
  'ulgrim': ['Axe', 'Rocket Lance'],
  'val': ['Gauntlets', 'Sword'],
  'vector': ['Bow', 'Rocket Lance'],
  'volkov': ['Axe', 'Scythe'],
  'wu shang': ['Gauntlets', 'Spear'],
  'xull': ['Axe', 'Cannon'],
  'yumiko': ['Bow', 'Hammer'],
  'zariel': ['Bow', 'Gauntlets'],
}

export { weaponMap };